dashboard/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('pahinungod_home', views.dashboard, name="dashboard")
]

pahinungod_forms/urls.py
from django.contrib import admin
from django.urls import include, path
from volunteer_forms.views import homePage
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', homePage),
    path('admin/', admin.site.urls),
    path('volunteer/', include('volunteer_forms.urls')),
    path('partners/', include('partners_forms.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/social/login/cancelled/', homePage, name="cancel_login"),
    path('accounts/', include('allauth.urls')),
]

partners_forms/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('logout_page/', views.logOutPage, name="log_out"),

    # PARTNERS
    path('view_partners/', views.view_partners, name='view_partners'),
    path('partner_form/', views.partner_form, name='partner_form'),

    ## CRUD
    path('add_partner/', views.add_partner, name='add_partner'),
    path('del_partner/<int:partner_id>', views.del_partner, name='del_partner'),
    path('upd_partner/<int:partner_id>', views.upd_partner, name='upd_partner'),

    ## Other Func.
    path('get_second_category_options/', views.get_second_category_options , name='get_second_category_options'),
    path('filter/', views.filterPartners , name='filterPartners'),

    # TYPE OF PARTNERS
    path('type_form/', views.type_partner_form, name='type_partner_form'),
    path('add_type/', views.add_type, name='add_type'),
    path('del_type/<int:type_id>', views.del_type, name='del_type'),
    path('upd_type/<int:type_id>', views.upd_type, name='upd_type'),
    
    # MISC.
    # path('del_all/', views.del_all, name='del_all'),
    # path('view-pdf/', views.pdf_view, name='pdf_view'),
]

urlpatterns += staticfiles_urlpatterns()

partners_forms/models.py
import datetime
import os
from typing import Any
from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# from django import forms

# Create your models here.
    
# FOR PARTNER TYPE
class Type(models.Model):
    type_code = models.CharField(max_length=5)
    type_of_partnership = models.CharField(max_length=64)

    def save(self, *args, **kwargs):
        if self.type_code:
            self.type_code = self.type_code.upper()

        super(Type, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.type_code} : {self.type_of_partnership}"
    
# FOR SCOPE OF WORK
class Scope_of_work(models.Model):
    Lecture = 'Lecture'
    Training = 'Training'
    Workshop = 'Workshop'
    Others = 'Others'
    
    scope_of_work_choices = [
        (Lecture, 'Lecture'),
        (Training, 'Training'),
        (Workshop, 'Workshop'),
        (Others, 'Others'),
    ]

# FOR MULTIPLE FILE FIELD
class Multiple_file_field(models.FileField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self, value, instance):
        if value:
            if isinstance(value, (list, tuple)):
                cleaned_files = []
                for file in value:
                    try:
                        self.run_validators(file)
                        cleaned_files.append(file)
                    except ValidationError as e:
                        raise ValidationError({self.name: e})
                return cleaned_files
            else:
                try:
                    self.run_validators(value)
                    return [value]
                except ValidationError as e:
                    raise ValidationError({self.name: e}) 
        else:
            return []

# PARTNER OBJ
class Partner(models.Model):

    # PARTNER NAME
    partner_name = models.CharField(max_length=64)

    # PARTNERSHIP EXTENSION
    partnership_extension_choices = [
        ('', 'Select Partnership Extension'),
        ('Health Training: Basic Life Support', 'Health Training: Basic Life Support'),
        ('Health Training: Breast Advocacy and PFA', 'Health Training: Breast Advocacy and PFA'),
        ('Health Training: FAST', 'Health Training: FAST'),
        ('Health Education: Oral Health', 'Health Education: Oral Health'),
        ('Health Education: MHPS', 'Health Education: MHPS'),
        ('Disaster Preparedness Training', 'Disaster Preparedness Training'),
        ('Disaster Preparedness Lecture', 'Disaster Preparedness Lecture'),
    ]

    partnership_extension = models.CharField(max_length=64, choices=partnership_extension_choices, blank=False)

    # STAKEHOLDER CATEGORY
    stakeholder_category_choices = [
        ('', 'Select Stakeholder Category'),
        ('Private', 'Private'),
        ('Government', 'Government'),
    ]

    second_category_choices = [
        ('', 'Select Second Stakeholder Category'),
        ('NGO', 'NGO',),
        ('Company', 'Company'),
        ('Educational Institution (Private)', 'Educational Institution (Private)'),
        ('LGU', 'LGU'),
        ('National Government Agency', 'National Government Agency'),
        ('Educational Institution (Government)', 'Educational Institution (Government)'),
        ('Others', 'Others'),
    ]
        
    stakeholder_category = models.CharField(max_length=64, 
                                            choices=stakeholder_category_choices, 
                                            null=True,
                                            blank=False)
    second_category = models.CharField(max_length=64, 
                                       choices=second_category_choices, 
                                       null=True,
                                       blank=False)
    other_choice = models.CharField(max_length=64, 
                                    blank=True,)
    
    # Extra Fields
    type_of_partnership = models.ManyToManyField(Type, blank=True)
    # scope_of_work = models.ManyToManyField(Scope_of_work, blank=True)

    # Date Field
    Agreement_Start_Date = models.DateField(default=datetime.date.today, null=False, blank=False)
    Agreement_End_Date = models.DateField(null=False, blank=False)

    # FOREIGN KEY FOR EACH PARTNER
    # Files = models.ForeignKey(Files_obj, on_delete=models.CASCADE, related_name='files') # ano lalagay dito HAHAHA

    def __str__(self):
        return f"{self.partner_name}"

# FOR FILES
class File(models.Model):
    # File Field
    file_field = models.FileField(upload_to="partners_forms/static/partner_requirements") # upload to where?
    file_name = models.CharField(max_length=64,blank=True,null=True)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE, related_name='partner', blank=True, null=True,)

    def save(self, *args, **kwargs):
        if self.file_field:
            self.file_name = os.path.basename(self.file_field.name)

        super(File, self).save(*args, **kwargs)

    def delete_file(self, *args, **kwargs):
        path = "./partners_forms/static/partner_requirements/" + self.file_name
        print(f'filename: {path}')

        os.remove(path)
        super(File, self).delete(*args, **kwargs)

partners_forms/views.py
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from partners_forms.forms import PartnerForm, Type_of_partnerForm, FilesForm
from .models import Partner, Scope_of_work, Type, File
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import logout
from django.conf import settings
from django.db.models import Q
from django.core.paginator import Paginator
import os

def is_superuser(user):
    return user.is_authenticated and (user.is_superuser or user.is_staff)

def is_auth(user):
    return not user.is_authenticated

# Create your views here.
# WEB PAGES ================================================================================================================

# PARTNERSHIP EXTENSION
partnership_extension_choices = [
    ('Health Training: Basic Life Support', 'Health Training: Basic Life Support'),
    ('Health Training: Breast Advocacy and PFA', 'Health Training: Breast Advocacy and PFA'),
    ('Health Training: FAST', 'Health Training: FAST'),
    ('Health Education: Oral Health', 'Health Education: Oral Health'),
    ('Health Education: MHPS', 'Health Education: MHPS'),
    ('Disaster Preparedness Training', 'Disaster Preparedness Training'),
    ('Disaster Preparedness Lecture', 'Disaster Preparedness Lecture'),
]

# STAKEHOLDER CATEGORY
stakeholder_category_choices = [
    ('Private', 'Private'),
    ('Government', 'Government'),
]

second_category_choices = [
    ('NGO', 'NGO',),
    ('Company', 'Company'),
    ('Educational Institution (Private)', 'Educational Institution (Private)'),
    ('LGU', 'LGU'),
    ('National Government Agency', 'National Government Agency'),
    ('Educational Institution (Government)', 'Educational Institution (Government)')
]

pagination_count = 5

@user_passes_test(is_superuser, login_url='home_vol')
def home_page(request):
    return render(request, "home.html")

@user_passes_test(is_auth, login_url='dashboard')
def admin_login(request):
    return render(request, "admin_login.html")

def logOutPage(request):
    if request.user.is_superuser or request.user.is_staff:
        logout(request)
        return redirect('admin_login')
    else:
        logout(request)
        return redirect('home_vol')

@user_passes_test(is_superuser, login_url='home_vol')
def view_partners(request):
    partners_list = {}
    partners = Partner.objects.all()

    for partner in partners:
        files = File.objects.filter(partner=partner)
        partners_list[partner] = files

    print(f'partners list: {partners_list}')

    p = Paginator(partners, pagination_count)
    page = request.GET.get("page")
    partners = p.get_page(page)

    types = Type.objects.all()

    # return render(request, "view_partners.html", {'partners' : partners})
    return render(request, "view_partners.html", {'partners' : partners, 
                                                  'types' : types,
                                                  'partners_list' : partners_list, 
                                                  'partnership_extension_choices': partnership_extension_choices,
                                                  'stakeholder_category_choices' : stakeholder_category_choices,
                                                  'second_category_choices' : second_category_choices})

@user_passes_test(is_superuser, login_url='home_vol')
def partner_form(request): # toPartnerForm Questionnairre
    scope_of_work_choices = Scope_of_work.scope_of_work_choices
    # print(f'scope_of_work_choices: {scope_of_work_choices}')
    return render(request, "partners_forms.html", {'form' : PartnerForm()
    , 'file_form': FilesForm(),'scope_of_work_choices': scope_of_work_choices})

@user_passes_test(is_superuser, login_url='home_vol')
def type_partner_form(request): # toTypePartnerForm Questionnairre
    types = Type.objects.all()
    return render(request, "type_of_partnership_form.html", {'types': types,'form': Type_of_partnerForm(), 'action' : "Add"})

# TYPE OF PARTNERSHIP ================================================================================================================
@user_passes_test(is_superuser, login_url='home_vol')
def add_type(request):
    form = Type_of_partnerForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            print('valid')
            form.save()
            return HttpResponseRedirect(reverse('type_partner_form'))
        else:
            return render(request, 'type_of_partnership_form.html', {'form': form, 'action' : "Add"})

@user_passes_test(is_superuser, login_url='home_vol')
def del_type(request, type_id):
    if request.method == 'POST':
        to_delete = Type.objects.get(pk=type_id)
        to_delete.delete()
        # return HttpResponseRedirect(reverse('type_partner_form'))
        return redirect('type_partner_form')

@user_passes_test(is_superuser, login_url='home_vol')   
def upd_type(request, type_id):
    # print(type_id)
    to_update = Type.objects.get(pk=type_id)
    # print(to_update)
    type_form = Type_of_partnerForm(request.POST or None, instance=to_update) # fields
    # print(type_form)
    all_types = Type.objects.all()

    if request.method == 'POST':
        if type_form.is_valid():
            print('type is valid')
            type_form.save()
            return HttpResponseRedirect(reverse('type_partner_form'))
    else:
        return render(request, 'type_of_partnership_form.html', {'type': to_update, 'types': all_types , 'form': type_form, 'action' : "Edit"})
        # return render(request, 'type_of_partnership_form.html', {'type': to_update, 'form': type_form})  

# PARTNER ================================================================================================================
@user_passes_test(is_superuser, login_url='home_vol')
def add_partner(request):
    if request.method == 'POST':
        form = PartnerForm(request.POST)
        uploaded_files = request.FILES.getlist('file_field')

        if form.is_valid():
            print('partner valid')
            # print(form.cleaned_data)  # Print cleaned form data
            partner_instance = form.save()
            partner_instance = Partner.objects.get(pk=partner_instance.id)
            print(f'partner instance: {partner_instance}')

            for fi in uploaded_files:
                file_dict = {'file_field': fi}

                files_form = FilesForm(request.POST, file_dict)
                if files_form.is_valid():
                    file_instance = files_form.save()

                form_that_save = File.objects.get(pk=file_instance.id)
                form_that_save.partner = partner_instance
                form_that_save.save()
        
        else:
            print('partner not valid')
            print(form.cleaned_data)  # Print cleaned form data

            for field, errors in form.errors.items():
                # Print error messages for each field
                for error in errors:
                    print(f"Field '{field}': {error}")

            # Form is not valid, render the form again with error messages
            return render(request, 'partners_forms.html', {'form': form, 'file_form': files_form})

        return HttpResponseRedirect(reverse('view_partners'))
        
    else:
        form = PartnerForm()
        files_form = FilesForm()

    return render(request, 'partners_forms.html', {'form': form, 'file_form': files_form})

@user_passes_test(is_superuser, login_url='home_vol')
def upd_partner(request, partner_id):
    # Instances
    to_update = Partner.objects.get(pk=partner_id) # Partner Instance
    # print(f'to update: {partner_id}')
    uploaded_files = File.objects.filter(partner=to_update) # Files Instance
    # print(f'to update: {uploaded_files}')
    updated_files = request.FILES.getlist('file_field')
    print(f'updated files: {updated_files}')

    # If ok ung mga fields
    if request.method == 'POST':
        # Forms
        form = PartnerForm(request.POST or None, instance=to_update) # Partner Form
        # files_form = FilesForm(request.POST or None, instance=uploaded_files)

        if form.is_valid():
            print('partner valid')
            partner_instance = form.save()
            partner_instance = Partner.objects.get(pk=partner_instance.id)
            # print(f'partner instance: {partner_instance.id}')

            # Delete Document
            for file in uploaded_files:
                # file.delete()
                file.delete_file()

            # Update
            for fi in updated_files:
                # Dictionary of files
                file_dict = {'file_field': fi}

                files_form = FilesForm(request.POST or None, file_dict)
                if files_form.is_valid():
                    print('files is valid')
                    file_instance = files_form.save()
                    print(f'file instance: {file_instance}')
                else:
                    print(f'File form errors: {files_form.errors}')
                
                form_that_save = File.objects.get(pk=file_instance.id)
                form_that_save.partner = to_update
                form_that_save.save()

            return HttpResponseRedirect(reverse('view_partners'))
    
    # If papunta sa form
    else:
        form = PartnerForm(instance=to_update) # fields
        files_form = FilesForm(request.POST or None, request.FILES)

        # Render the form again with error messages
        return render(request, 'update_partners.html', {'partner': to_update, 'form': form, 'file_form': files_form})

@user_passes_test(is_superuser, login_url='home_vol')
def del_partner(request, partner_id):
    if request.method == 'POST':
        to_delete = Partner.objects.get(pk=partner_id)
        files = File.objects.filter(partner=to_delete)

partners_forms/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login Page</title>
</head>

<style>
    .body {
        background-color: #FCF5E5;
    }

    .center-panel {
        background: rgba(255, 255, 255);
        border-radius: 16px;
        display: inline-block;
        cursor: pointer;

    }

    .circular--square { 
        border-style: solid;
        border-radius: 50%; 
        border-width: thick;
        border-color: #021d0f;
        border-image-width: 20%;
        margin-bottom: -20px;
        z-index: 1;
        padding: 10px;
        min-width: 20%;
    }

    #red-color {
        color: #7B0100;
        background-color: #7B0100;
        box-sizing: border-box;
    }

    #dark-green-color {
        color: #023219;
        background-color: #023219;
    }
    
    #parchment {
        color: #FCF5E5;
    }

    .img-bg {
        position: absolute;
        /* background-image: url('/static/partners_forms/media/Overview.jpg'); */
        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover;
        object-fit: cover;
        /* max-width: 100%; */
        /* max-height: 100%; */
        width: 100%;
        height: 100vh;
        /* position: absolute; */
        z-index: -1;
        opacity: 0.3;
        background-attachment: fixed;
        
        /* Add the blur effect */
        filter: blur(8px);
        -webkit-filter: blur(8px);
    }


</style>

<body class="body">
    <!-- IMPORTS -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    {% load socialaccount %}

    <!-- <h1 class="display-1 text-center">Pahinungod Forms</h1> -->
    
    <!-- BG IMAGE -->
    <img src="/static/partners_forms/media/Overview.jpg" alt="Pahinungod Background Overview" class="img-bg">
    
    <div class="d-flex flex-column align-items-center vh-100 justify-content-center" style="height: 100%">

        <img src="{% static 'partners_forms/media/admin_icon.png' %}" alt="Admin Icon" class="min-vw-70 circular--square" style="background-color: #023219; 
        display: block;
        max-width: 50%; 
        min-width: 13%;
        margin-top: -100px; 
        margin-left: auto; 
        margin-right: auto;
        width: 15%;
        ">

        <!-- CENTER PANEL -->
        <div class="d-flex flex-column align-items-center justify-content-center" style="height: auto; width: 50%;">
            <div class="d-flex-col h-100 w-auto p-3" id="red-color" style="border-style: solid; border-radius: 16px 16px 16px 16px; border-width: thick; border-color: #490202;">


                <h1 class="display-5 text-white text-center py-3 mx-sm-4">Pahinungod Forms</h1>
                <p class="text-white pb-3 mx-sm-4" style="text-align: justify;">Lorem ipsum dolor sit amet. Non ratione doloribus et quos nihil ut expedita iure! Et tempore suscipit ea rerum sint et officia cumque et rerum voluptatem hic corporis voluptas eos deserunt veniam et quod quasi. </p>

                
            
                <form id="login_form" action="{% provider_login_url 'google' %}" style="z-index: 1;">
                    <div class="btn d-flex flex-column py-2 m-sm-4" style="background-color: #f1a92b;">            
                            <h5 id="parchment" style="color:#023219; margin: auto;">Admin Login/Sign Up</h5>
                    </div>
                </form>
            </div>
            

        </div>
        
    </div>

</body>

<script>
    const form = document.getElementById('login_form');     
    const div = document.getElementById('red-color');

    div.addEventListener('click', () => {
        form.submit();
    })

</script>

</html>

partners_forms/templates/base_partner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Partners Form</title>
</head>

<style>
    .img {
        width: 100px;
        height: auto;
    }
</style>

<body>
    <!-- IMPORTS -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    
    <!-- HEADER -->
    <div class="mb-6" style="background-color: #7B0100;">
        <a href="{% url 'home' %}" class="d-flex align-items-center" style="text-decoration: none; color: white">
            <img src="{% static 'partners_forms/media/admin_icon.png' %}" alt="Admin Icon" class="img" style="background-color: #7B0100;">
            <h1 class="h1">Admin Dashboard</h1>
        </a>
    </div>

    <!-- NAVBAR -->
    <div style="background-color: #262626;">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link text-white" id="home" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" id="partners" href="{% url 'view_partners' %}">Partners</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" id="partner_form" href="{% url 'partner_form' %}">Add Partners</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" id="type_of_partner_form" href="{% url 'type_partner_form' %}">Add Type Partners</a>
            </li>
        </ul>
    </div>

    {% block content %}

    {% endblock %}
</body>
</html>

partners_forms/templates/home.html
{% extends 'base_dashboard.html' %}

{% block content %}

<div class="border">
    <h1>Home</h1>
    <h2> About: </h2>
    <h3>
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    </h3>
</div>

<script>
    // document.getElementById('home').classList.remove('nav-link')
    // document.getElementById('home').classList.add('nav-link active')
    
    document.getElementById('home').className += ' active bg-secondary'

</script>


{% endblock %}

partners_forms/templates/partners_forms.html
<!-- Extensions -->
{% extends 'base_dashboard.html' %}
{% load widget_tweaks %}

{% block body %}

    <style>
        .form_div{
            margin: auto;
        }

        input, select {
            margin-bottom: 2%;
        }

        table, tr, td{
            border: 2px solid black;
            border-collapse: collapse;
            margin: auto;
        }

        @media (max-width: 768px) {
            .hide_date_field {
                display: none;
            }
        }

        

    </style>

    <h1 style="margin: auto; text-align: center;"> Partner Form </h1>

        <form action="{% url 'add_partner' %}" enctype="multipart/form-data" method="POST" class="
        mb-3 p-4 
        d-flex flex-column 
        align-items-center justify-content-center border"> 
            {% csrf_token %}
    
            <!-- TABLE FORM -->
                <!-- <table>
                    <tr>
                        <td>
                            <label for="id_partner_name">Partner Name: </label>
                            {{ form.partner_name }}
                        </td>
                        <td>
                            <label for="id_partnership_extension">Partnership Extension</label>
                            {{ form.partnership_extension }}
                        </td>
                    </tr>    
    
                    <tr>
                        <td>  </td>
    
                    </tr>
    
        
                </table> -->

                <!-- Overall Div -->
                <div class="mb-3 w-75 flex-column d-flex align-items-center justify-content-center">
                    
                    {{ form.partner_name }}
 
                    {{ form.partnership_extension }}

                    {{ form.stakeholder_category }}

                    {{ form.second_category }}

                    {{ form.other_choice }}

                    <!-- Type of Partnership Field -->
                    <div class="d-inline-flex flex-column w-100">
                        <label for="id_type_of_partnership" class="col-auto col-form-label">Type of Partnership: </label>
                        <div class="col-sm-100">
                            {{ form.type_of_partnership }}
                        </div>
                    </div>

                    <!-- Date Fields -->

                    <!-- MOBILE VIEW -->
                    <div class="mb-2 form-row align-items-center justify-content-center d-flex-col">
                        <div class="form-group row col-auto m-2">
                            <!-- Start Date -->
                            <label for="id_Agreement_Start_Date" class="col-auto col-form-label">Start Date</label>
                            <div class="col-auto">
                                {% render_field form.Agreement_Start_Date type="date" class='form-control' placeholder="mm/dd/yyyy" %}
                            </div>        
                        </div>
                        <div class="form-group row col-auto m-2">
                            <!-- End Date -->
                            <label for="id_Agreement_End_Date" class="col-auto col-form-label">End Date</label>
                            <div class="col-auto">
                                {% render_field form.Agreement_End_Date type="date" class='form-control' placeholder="mm/dd/yyyy" %}
                            </div>
                        </div>
                    </div>
                    
                    <!-- File Field -->
                    {{ file_form.file_field }}

                </div>
                
    
            
    
            <input type="submit">
        </form>

        <!-- {{ form.as_p }} -->

    <script>

        document.getElementById('partner_form').className += ' active bg-secondary'

        // FIELDS
        // SelectElement
        const selectElement = document.getElementById('id_stakeholder_category');
        // console.log(selectElement)

        // selectElement_second 
        const selectElement_second = document.getElementById('id_second_category');
        const selectElement_second_options = selectElement_second.options;
        selectElement_second.style.display = 'none'; // Hide all second element (including options)

        // otherField
        const otherField = document.getElementById('id_other_choice');
        const otherFieldLabel = document.querySelector('label[for="id_other_choice"]');
        otherField.style.display = 'none';

        const private = ['NGO', 'Company', 'Educational Institution (Private)', 'Others'];

        const government = ['LGU', 'National Government Agency', 'Educational Institution (Government)', 'Others'];

        document.addEventListener('DOMContentLoaded', function() {

            // Hide second options
            function hide_second_options(){
                for (let i = 0; i < selectElement_second_options.length; i++) {
                    const option = selectElement_second_options[i];
                    option.style.display = 'none';
                }
            } 
            hide_second_options();

            function show_others_field(){
                otherField.style.display = 'block';
            }
            
            // Listen to stakeholder_category selected (P and G)
            selectElement.addEventListener('change', function(event) {

                const selectedValue = event.target.value;
                console.log(selectedValue)

                // Check value of stakeholder_category
                if(selectedValue == 'Private'){
                    console.log('HERE IN P')  
                    selectElement_second.style.display = 'block';
                    for (let i = 0; i < selectElement_second_options.length; i++) {
                    const option = selectElement_second_options[i];
                    // console.log(option)
                        if (private.includes(option.value)) {
                            option.style.display = 'block';
                        } else{
                            option.style.display = 'none';
                        }
                    }
                } else if(selectedValue == 'Government'){
                    console.log('HERE IN G')  
                    selectElement_second.style.display = 'block';
                    for (let i = 0; i < selectElement_second_options.length; i++) {
                    const option = selectElement_second_options[i];
                        if (government.includes(option.value)) {
                            option.style.display = 'block';
                        }else{
                            option.style.display = 'none';
                        }
                    }
                } else{
                    selectElement_second.style.display = 'none';
                    hide_second_options()
                }

                // Listen to selectElement_second selected (Under P and G)
                selectElement_second.addEventListener('change', function(event){

                    // Get the selected option from selectElement_second
                    const selectedOption = selectElement_second.options[selectElement_second.selectedIndex]

                    // Get the value and text of the selected option
                    const selectedValue = selectedOption.value;
                    console.log(selectedValue)
                    const selectedText = selectedOption.textContent.trim();
                    console.log(selectedText)

                    if(selectedText == 'Others'){
                        otherField.style.display = 'block';
                    } else{
                        otherField.style.display = 'none';
                    }

                });


            });
        });

        // Event listener for the change event
    </script>

{% endblock %}